import "./globals.css";
import localFont from "next/font/local";

const Lufga = localFont({
  src: [
    { path: "../fonts/lufga/LufgaThin.ttf", weight: "100", style: "normal" },
    {
      path: "../fonts/lufga/LufgaThinItalic.ttf",
      weight: "100",
      style: "italic",
    },
    {
      path: "../fonts/lufga/LufgaExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../fonts/lufga/LufgaExtraLightItalic.ttf",
      weight: "200",
      style: "italic",
    },
    { path: "../fonts/lufga/LufgaLight.ttf", weight: "300", style: "normal" },
    {
      path: "../fonts/lufga/LufgaLightItalic.ttf",
      weight: "300",
      style: "italic",
    },
    { path: "../fonts/lufga/LufgaRegular.ttf", weight: "400", style: "normal" },
    { path: "../fonts/lufga/LufgaItalic.ttf", weight: "400", style: "italic" },
    { path: "../fonts/lufga/LufgaMedium.ttf", weight: "500", style: "normal" },
    {
      path: "../fonts/lufga/LufgaMediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../fonts/lufga/LufgaSemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    { path: "../fonts/lufga/LufgaBold.ttf", weight: "700", style: "normal" },
    {
      path: "../fonts/lufga/LufgaBoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../fonts/lufga/LufgaExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../fonts/lufga/LufgaExtraBoldItalic.ttf",
      weight: "800",
      style: "italic",
    },
    { path: "../fonts/lufga/LufgaBlack.ttf", weight: "900", style: "normal" },
    {
      path: "../fonts/lufga/LufgaBlackItalic.ttf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-lufga",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${Lufga.variable} `}>{children}</body>
    </html>
  );
}
